version: "3.2"

services:
  influxdb:
    image: influxdb:1.8
    hostname: ${INFLUXDB_HOST}
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB
      - INFLUXDB_HTTP_AUTH_ENABLED
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
    restart: always
  grafana:
    build:
      context: "./grafana"
      args:
        - INFLUXDB_ADMIN_USER
        - INFLUXDB_ADMIN_PASSWORD
        - INFLUXDB_DB
        - INFLUXDB_HOST
    hostname: grafana
    image: ${HISTORIAN_GUI_REGISTRY_URI}:${VERSION_TAG}
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - INFLUXDB_DB
      - INFLUXDB_HOST
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
    depends_on:
      - ${INFLUXDB_HOST}
